{"name": "test_login_2_exception[item4]", "status": "passed", "parameters": [{"name": "item", "value": "{'user': '', 'pwd': '', 'Expected': '请输入手机号'}"}], "start": 1605260776817, "stop": 1605260777203, "uuid": "9d9b6932-54d3-43f7-84f9-4a45aee6e6e2", "historyId": "665668aacd9550aab69c64968d3678b2", "fullName": "Case.test_login_pytest.TestLogin#test_login_2_exception[item4]", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CP63FEL"}, {"name": "thread", "value": "10712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_login_pytest"}]}