{"name": "test_login_2_exception[item3]", "status": "passed", "parameters": [{"name": "item", "value": "{'user': '1868472055', 'pwd': 'python', 'Expected': '请输入正确的手机号'}"}], "start": 1605260775503, "stop": 1605260776003, "uuid": "e1612585-2da1-4471-ad20-2d6352dcaf3a", "historyId": "6d42d4d9806f961eb88093df1484debd", "fullName": "Case.test_login_pytest.TestLogin#test_login_2_exception[item3]", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CP63FEL"}, {"name": "thread", "value": "10712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_login_pytest"}]}