{"name": "test_login_2_exception[item2]", "status": "passed", "parameters": [{"name": "item", "value": "{'user': '186847205531', 'pwd': 'python', 'Expected': '请输入正确的手机号'}"}], "start": 1605260774053, "stop": 1605260774628, "uuid": "76c00ae3-f152-4d79-8de5-48e2f2bf073c", "historyId": "611535511be9d588d52da38970299211", "fullName": "Case.test_login_pytest.TestLogin#test_login_2_exception[item2]", "labels": [{"name": "parentSuite", "value": "Case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-CP63FEL"}, {"name": "thread", "value": "10712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Case.test_login_pytest"}]}